on:
  push:
    branches-ignore:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Automatic PR created on branch push
          branch: ${{ github.ref }}
          commit-message: Automatic PR created on branch push
          body: This pull request was automatically created when pushing changes to a branch.
